спринт 9: инкремент 23
Orendev/shortener pull request #27
Opened 2023-08-13 18:42 UTC by Orendev

2023-08-20 19:20 UTC, bambruysk requested changes
Нужно переписать часть связанную с асинхронным выполнением батч запроса. 

Смотрите в чем суть
Приходит пачка айдишников на удаление. Вы сразу сообщаете пользователю что все ок, а эту пачку потихоньку в отдельной горутинке запихиваете в канал. В **другой** же горутинке вы их постепенно выичтываете и делаете запросу в базу удобными для нее размерами. 

В чем суть паттерна -  запросы в базу у нас не зависят от размера запросов пользователей - мелкие запросы собираются в одну пачку, крупные режутся на несколько.  

Поправьте этот момент, при необходимости можем 1-1 сделать

2023-08-20 19:20 UTC, bambruysk commented on internal/handlers/apishorten.go
> +	numWorkers := len(codes) + 2
а почему воркеров больше на два чем кодов? в результате же  два юужут простаивать

2023-08-20 19:20 UTC, bambruysk commented on internal/handlers/apishorten.go
> +	}()
а зачем это все? мы бы могли просто записать в один поток в канал все данные?  Мне кажется вы не совсем поняли суть этого момента с батчами

2023-08-20 19:20 UTC, bambruysk commented on internal/handlers/apishorten.go
> +	}
вот к этому моменту у вас в urls - копия того что на входе

2023-08-21 08:47 UTC, Orendev commented on internal/handlers/apishorten.go
> +	}
поправил

2023-08-21 08:47 UTC, Orendev commented on internal/handlers/apishorten.go
> +	}()
переделал

2023-08-21 08:53 UTC, Orendev commented on internal/handlers/apishorten.go
> +	numWorkers := len(codes) + 2
поправил

2023-08-23 09:51 UTC, bambruysk approved these changes
принято.
Но лучше еще немного подумать над многопоточкой. Если есть вопросы - давай в личку)

2023-08-23 09:51 UTC, bambruysk commented on internal/handlers/apishorten.go
> +	inputCh := make(chan string, numWorkers)
Это получается не не колчиество воркеров, а размер буфера, в целом его можно сделать любым будет работать

2023-08-23 09:51 UTC, bambruysk commented on internal/handlers/apishorten.go
> +			}
канал закрылся - продолджать весь цикл не имеет смысла

2023-08-23 09:51 UTC, bambruysk commented on internal/handlers/apishorten.go
> +	h.flushDeleteShortLink(ctx, codeCh, userID)
вот этот вызов можно было бы сделать один раз в отдельном месте
Канал не пересоздавать на каждый вызов, а создать один раз и пусть в него все запросы пишут.

2023-08-23 09:51 UTC, bambruysk commented on internal/handlers/apishorten.go
> +				logger.Log.Info("cannot delete shortLink", zap.Error(err))
Если это ошибка то лучше logger.Log.Error(

2023-08-26 05:36 UTC, Orendev commented on internal/handlers/apishorten.go
> +			}
поправил

2023-08-26 05:36 UTC, Orendev commented on internal/handlers/apishorten.go
> +	h.flushDeleteShortLink(ctx, codeCh, userID)
переделал

2023-08-26 05:36 UTC, Orendev commented on internal/handlers/apishorten.go
> +				logger.Log.Info("cannot delete shortLink", zap.Error(err))
поправил

2023-08-26 05:37 UTC, Orendev commented on internal/handlers/apishorten.go
> +	inputCh := make(chan string, numWorkers)
переделал

2023-08-26 17:39 UTC, merged